#nullable enable

namespace Revu.Core.Models;

/// <summary>
/// A suggested learning objective generated by the suggestion engine.
/// </summary>
public class ObjectiveSuggestion
{
    public string Title { get; set; } = "";
    public string SkillArea { get; set; } = "";
    public string Type { get; set; } = "primary";
    public string CompletionCriteria { get; set; } = "";
    public string Description { get; set; } = "";
    public string Reason { get; set; } = "";
    public double Confidence { get; set; }
}
